### ISSUE TITLE
[BUG] Incorrect serialized aggregation response

### ISSUE THREAD

**Issue by chanon-onman** [opensearch-project/opensearch-java#1294]
### What is the bug?
`SearchResponse.toJsonString()` generates incorrect aggregation response that doesn't match with what is in the documentation. The `aggregation` keys have extra prefix, e.g. `lterms#`, `sterms#`.

### How can one reproduce the bug?
Execute the code below to get json serialized of search response.
```
SearchResponse resp = new SearchResponse.Builder<>()
        .aggregations("aggKey", v -> v.lterms(lv -> lv.buckets(b -> b.array(new ArrayList())).sumOtherDocCount(0)))
        .took(0)
        .timedOut(false)
        .shards(s ->s.failed(0).successful(1).total(1))
        .hits(h -> h.hits(new ArrayList()))
        .build();
System.out.println(resp.toJsonString());
```
The output is
```
{
  "took": 0,
  "timed_out": false,
  "_shards": {
    "failed": 0,
    "successful": 1,
    "total": 1
  },
  "hits": {
    "hits": []
  },
  "aggregations": {
    "lterms#aggKey": {    <--------*
      "buckets": [],
      "sum_other_doc_count": 0
    }
  }
}
```

### What is the expected behavior?
Aggregation keys should not have other prefix according to the document: https://opensearch.org/docs/latest/aggregations/

### What is your host/environment?
opensearch-java 2.17.0

**Comment by Xtansia** [comment]
This is not a bug but expected behavior, we (de)serialize aggregations following the behavior of the [`typed_keys` parameter on the search api](https://opensearch.org/docs/latest/api-reference/search/), this means aggregation keys are prefixed with their type so that there's no ambiguity in deserializing.

There is an existing issue #741 for adding a mechanism to disable the behavior.
