### ISSUE TITLE
[PROPOSAL] Release v2.1.0

### ISSUE THREAD

**Issue by Arsnael** [opensearch-project/opensearch-java#174]
Hi !

As suggested by @dblock here https://github.com/opensearch-project/opensearch-java/issues/158#issuecomment-1170494720, I would like to suggest a release of the 2.0.1 client.

I need particularly this commit as it's an issue in the current project I am working on:
- https://github.com/opensearch-project/opensearch-java/commit/3335c98eb647d50c04a3f747824b74e7f575921e

Maybe other people in the community need other stuff? 

Thank you :)

**Comment by dblock** [comment]
I renamed this to release 2.1.0, with #183 and #177 that we really want!

**Comment by garethcwilliams** [comment]
Any ETA on this release?

**Comment by dblock** [comment]
If we work fast it will be done today :) The Jenkins workflow we had used for the previous version is now borked, I just PRed #187 to fix it and get a -STAGING build along the way.

**Comment by dblock** [comment]
Looks like we have everything ready minus collecting release notes - @VachaShah did you collect these by hand for 2.0? We don't like releasing on Fridays because then nobody is here to fix any messes, will do first thing in the AM.

In the meantime, please try 2.1.0-SNAPSHOT that is now being automatically built and published with every commit to main? https://aws.oss.sonatype.org/content/repositories/snapshots/org/opensearch/client/opensearch-java/

**Comment by gaiksaya** [comment]
OpenSearch Java 2.1.0 is out https://repo1.maven.org/maven2/org/opensearch/client/opensearch-java/2.1.0/ 🎉 

Closing this issue!
