### ISSUE TITLE
[BUG] Nested/Sub Aggregations are not sending back buckets containing the data

### ISSUE THREAD

**Issue by joelbolt35** [opensearch-project/opensearch-java#197]
### What is the bug?
This is a duplicate bug from the elastic search java client:
https://github.com/elastic/elasticsearch-java/issues/87

### How can one reproduce the bug?
Create ANY nested aggregation for terms. There is no way to retrieve results

### What is the expected behavior?
Nested Queries work.

### What is your host/environment?
Linux (Ubuntu 18.04). Using opensearch-rest-clientv2.1.0 and opensearch-javav2.0.0

### Do you have any screenshots?
![Screenshot from 2022-08-01 12-05-28](https://user-images.githubusercontent.com/10093882/182191755-d5c2926f-d31c-4d7c-8efb-a71767fa4c82.png)
the docCount is correct but I can't see the data since the deserializer tossed it.

**Comment by dblock** [comment]
Would appreciate a PR with the fix. Please be mindful of not copying non-APLv2 code.

**Comment by joelbolt35** [comment]
@dblock
The elastic search specification update that this fix needed was fixed here: https://github.com/elastic/elasticsearch-specification/pull/1243

And I see here that they used code generation from that spec: https://github.com/elastic/elasticsearch-java/commit/7444423055b1826b147a1c104d96793aee5281f8

How is this code generation done? I need to generate it since this this code gen appears to fix the issue.

**Comment by dblock** [comment]
@joelbolt35 TBH I don't know. I don't think we generated any code here since the fork, and the spec has diverged. We thus don't want to use the upstream elasticsearch-specification. I suppose it would be ok to make small fixes by hand?

The long term plan I'd like to take is https://github.com/opensearch-project/opensearch-clients/issues/19. It's similar to what elastic is doing, except we chose different tooling. For opensearch-java this means swapping the elastic spec for https://github.com/opensearch-project/opensearch-api-specification (or its output). It would be amazing if someone could attempt that, even if to see what the gap is.

**Comment by pchaitu** [comment]
I am also struggling with the same issue with Nested and Multi term aggregation, as well, any chances of quick fix on this?

**Comment by abhinav-nath** [comment]
Can someone please help - how to parse sub-aggregations from filter aggregations? This is a big issue for rendering multi-select facets and refraining me from using this new client.

**Comment by abhinav-nath** [comment]
@dblock - I have create a PR (https://github.com/opensearch-project/opensearch-java/pull/234). Please review it.

**Comment by oana-danescu-idnow** [comment]
Any idea when this will be released?

**Comment by dblock** [comment]
Please add your +1 to https://github.com/opensearch-project/opensearch-java/issues/253

**Comment by VachaShah** [comment]
This was released in [v2.2.0](https://github.com/opensearch-project/opensearch-java/releases/tag/v2.2.0).
