### ISSUE TITLE
[FEATURE] Add IAM authentication option / support for SigV4 Signer

### ISSUE THREAD

**Issue by aetter** [opensearch-project/opensearch-java#55]
If people want to connect to an Amazon OpenSearch Service cluster, they have to figure out how to use this client alongside some third-party signing library and/or the AWS SDK, which is non-trivial due to how we (by design) conceal the underlying HTTP requests that the client makes. We should offer IAM signing as an option, just like the OpenSearch CLI does.

**Is your feature request related to a problem?**
If you want to use this client with an Amazon OpenSearch Service cluster that has IAM authentication rather than basic authentication, good luck.

**What solution would you like?**

When initializing the client, accept an AWS IAM credential provider and sign requests automatically.

**What alternatives have you considered?**

An additional Java signing library for use on top of the client. But given that it would only work with the client, it seems better and easier to just add it to the client.

**Do you have any additional context?**

https://github.com/opensearch-project/OpenSearch/issues/1400

**Comment by SingingBush** [comment]
this is an essential requirement.

**Comment by dblock** [comment]
Please contribute!

**Comment by mtimmerm** [comment]
@dblock I solved this problem by writing an implementation of `OpenSearchTransport` that uses `SdkHttpClient` from the AWS v2 SDK to send signed requests, instead of the default client.  It seemed more straightforward than the interceptor implementations.

I can contribute it if that's the way you'd like it solved in this library.

**Comment by dblock** [comment]
@mtimmerm Yes definitely! 

Related, I've been trying to resurrect a fork of archived https://github.com/awslabs/aws-request-signing-apache-interceptor in https://github.com/acm19/aws-request-signing-apache-interceptor. Are you saying we would not need an interceptor at all? Do you have a minimal working example?

**Comment by mtimmerm** [comment]
Yes, that's right -- no interceptor at all, but a new transport implementation.  I'll get my boss to approve contributing it and then put up something for you.  

I'm not sure what we're going to do about integration tests, since it will require an AWS OpenSearch cluster to connect to.

**Comment by mtimmerm** [comment]
PR: https://github.com/opensearch-project/opensearch-java/pull/177

A added integration tests gated by a system property.  They will be skipped unless you specify a target OpenSearch domain.

**Comment by mtimmerm** [comment]
Since AWS Signature V4 requires a hash of the request payload, does chunked transfer encoding provide any benefit?  If you can calculate the hash, you can calculate the Content-Length.

W.r.t. compressed requests -- my transport does not compress request at the moment.  It would be reasonable to automatically compress requests bigger then 8kB or so, but I don't know how to sign them.  Does your demo work?  Can you compress all requests to OpenSearch service?  If so, then that functionality can be incorporated into the transport.

I would implement compression in the OutputStream that gets passed to JsonpMapper for serialization.  It would start delegating to a ByteArrayOutputStream, and if it gets more than 8K then it would insert a GzipOutputStream in front.  This way we never need to allocate an array as big as the uncompressed request.

**Comment by dblock** [comment]
> Since AWS Signature V4 requires a hash of the request payload, does chunked transfer encoding provide any benefit? If you can calculate the hash, you can calculate the Content-Length.

I could be wrong, but I believe for chunked requests Sigv4 starts by online signing the headers, then incrementally signing every chunk based on the previous chunk's signature. You can know the size of your data ahead of time, e.g. file size. And since you never need to sign the entire content you never need to load it into memory.

> W.r.t. compressed requests -- my transport does not compress request at the moment. It would be reasonable to automatically compress requests bigger than 8kB or so, but I don't know how to sign them. Does your demo work? Can you compress all requests to OpenSearch service? If so, then that functionality can be incorporated into the transport.

The code in https://github.com/dblock/aws-sdk-sigv4-demo/blob/master/src/main/java/org/dblock/AmazonOpenSearchServiceSample.java#L45 works. Feel free to add before/later.

> I would implement compression in the OutputStream that gets passed to JsonpMapper for serialization. It would start delegating to a ByteArrayOutputStream, and if it gets more than 8K then it would insert a GzipOutputStream in front. This way we never need to allocate an array as big as the uncompressed request.

👍

**Comment by dblock** [comment]
Closing via #177.

**Comment by MaxKsyunz** [comment]
Are the integration tests being run as part of the build process?

There's a PR -- opensearch-project/opensearch-net#66 -- that adds SIGv4 to .NET client. It'd be great if it had the same test coverage as the Java implementation.

**Comment by dblock** [comment]
Unfortunately we're not. I opened https://github.com/opensearch-project/opensearch-clients/issues/31. We need infrastructure and a login to do that.

**Comment by dblock** [comment]
Note https://github.com/awsdocs/amazon-opensearch-service-developer-guide/pull/66 that is PRed into the AWS service doc.
